### ISSUE TITLE
[Question] Why delete /config/haskell.nix?

### ISSUE THREAD

**Issue by jjant** [jwiegley/nix-config#7]
I noticed you deleted the haskell.nix file with all the haskell packages, I was planning on using a similar thing so I wondered why you deleted this.

Thanks

**Comment by jwiegley** [comment]
Hi @jjant, thanks for asking.

I used to build mondo Haskell environments, with tons of packages included, so that I could jump around and edit multiple projects in Emacs and it would all be seamless. As well as upgrading everything at once.

However, I started running into command-line length limits on macOS, which artificially capped how long that packages list could get. This was most unfortunate, as it required dropped packages I did want in order to get those I most needed.

When I discovered [direnv](https://direnv.net/), and found out how well it can integrates with Nix and Emacs (using [emacs-direnv](https://github.com/wbolster/emacs-direnv)), I realized that I could have a separate environment for every project -- using just the packages it needs -- and yet still have almost the same user experience as before. This was even better than the mondo environment, because many of my projects are pinned to specific nixpkgs versions, whereas others don't need pinning and can use whatever is most current.

After several months of not using the mondo environments at all, I dropped them to simplify the configuration.

**Comment by toonn** [comment]
My main reason for sticking to that approach is the local hoogle. My `package-list.nix` is mostly packages I evaluated as being the best choice for me and some that just happen to be required to work on other projects.
This means that if my local hoogle has a good result I already have that dependency installed, so no fuss with getting it installed/jailbreaking/dontchecking, and more importantly I've likely already vetted the package so I don't have to go on a tangent finding out all the alternatives and evaluating them.

Is this still possible with the direnv approach?

**Comment by jwiegley** [comment]
So far I've had no issues with the direnv approach, which provides a Hoogle tailored to each project.

**Comment by toonn** [comment]
So no way to get a hoogle for every package you have in the store? That's too bad because of what I described. You win some, you lose some, I guess.
