### ISSUE TITLE
Another question about Emacs

### ISSUE THREAD

**Issue by rajivr** [jwiegley/nix-config#8]
Firstly, thanks a lot for all the awesome open source software over the years.

I am new to Nix (and NixOS) and I am trying to learn from your Nix setup.

I took a look at #2 and [`config/packages.nix`](https://github.com/jwiegley/nix-config/blob/master/config/packages.nix). 

I was unable to figure out how the `emacs` derivation gets installed? Would you be share how/where `emacs` derivation gets installed?

**Comment by jwiegley** [comment]
On my system, I install a `myEnvFun` named `emacs26Env`. You'll find that defined in `overlays/10-emacs.nix`, and used in `config/envs.nix`.

Note that I used to use `myEnvFun` a lot more than I do now, since for most things I just rely on `nix-shell` by way of `direnv` and `emacs-direnv`. But Emacs is still something that I need to run two of (both HEAD and stable), at the same time, so I use `myEnvFun` to produce a shell script that runs each Emacs within its own full environment.

**Comment by rajivr** [comment]
Thanks @jwiegley!
